# Generated by Django 4.2.28 on 2026-02-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese'), ('it', 'Italian'), ('ru', 'Russian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('ms', 'Malay'), ('fil', 'Filipino'), ('my', 'Burmese'), ('ar', 'Arabic'), ('he', 'Hebrew'), ('fa', 'Persian'), ('tr', 'Turkish'), ('nl', 'Dutch'), ('pl', 'Polish'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('fi', 'Finnish'), ('el', 'Greek'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('uk', 'Ukrainian'), ('bg', 'Bulgarian'), ('sk', 'Slovak'), ('hr', 'Croatian'), ('sl', 'Slovenian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian'), ('ca', 'Catalan'), ('ga', 'Irish'), ('cy', 'Welsh'), ('sw', 'Swahili'), ('af', 'Afrikaans'), ('am', 'Amharic'), ('zu', 'Zulu')], default='en', max_length=10),
        ),
    ]
