# Generated by Django 4.2.28 on 2026-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0003_voiceclone_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedspeech',
            name='balance_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedspeech',
            name='credits_used',
            field=models.IntegerField(default=5),
        ),
    ]
