# Generated by Django 4.2.28 on 2026-02-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0004_generatedspeech_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprofile',
            name='sample_audio',
            field=models.FileField(blank=True, null=True, upload_to='voiceprofile_audio/'),
        ),
    ]
