import React from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { ShieldAlert } from 'lucide-react';

export function Disclaimer() {
  return (
    <div className="min-h-screen pt-24 pb-12 px-4">
      <div className="container mx-auto max-w-4xl">
        <h1 className="text-3xl font-bold mb-8 gradient-text">Disclaimer</h1>
        
        <Card className="glass border-white/10">
          <CardContent className="p-8 prose prose-invert max-w-none">
            <div className="mb-6 bg-amber-500/10 border border-amber-500/50 text-amber-500 p-4 rounded-lg flex gap-3 items-start">
                <ShieldAlert className="h-5 w-5 mt-0.5 shrink-0" />
                <div>
                   <h5 className="font-bold mb-1 text-amber-500">Important Use Restriction</h5>
                   <p className="text-sm m-0">VoiceAI technology must not be used to generate deceptive content or deepfakes intended to mislead.</p>
                </div>
            </div>

            <h3>1. AI Generated Content</h3>
            <p>The voices and audio generated by our service are created by Artificial Intelligence. While we strive for realism, the outputs are synthetic and should not be represented as authentic recordings of the individuals whose voices may be mimicked without their explicit consent.</p>

            <h3>2. No Misuse</h3>
            <p>You agree NOT to use this service to:</p>
            <ul>
                <li>Create content that promotes hate speech, violence, or illegal acts.</li>
                <li>Impersonate others for fraudulent purposes (e.g., vishing, scams).</li>
                <li>Generate sexual or non-consensual explicit content.</li>
            </ul>

            <h3>3. Liability Limitation</h3>
            <p>VoiceAI provides this service "as is". We are not liable for how users utilize the generated content. Users are solely responsible for ensuring their use of the generated audio complies with all applicable laws and regulations.</p>

             <h3>4. Voice Cloning Consent</h3>
            <p>When using our voice cloning feature, you certify that you have the necessary rights or consent from the voice owner to create a digital replica.</p>
            
            <p className="text-sm text-muted-foreground mt-8">Last updated: {new Date().toLocaleDateString()}</p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

export default Disclaimer;
